config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :books do
    collection do
      get :collection
      get :wishlist
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  scope :in_my_collection, -> { where(in_my_collection: true) }
  scope :wishlist, -> { where(wishlist: true) }

  def self.create_from_collection(books)
    books.each do |book_hash|
      Book.create!(book_hash)
    end
  end
end

app/models/scraper.rb
require "open-uri"
require "nokogiri"
# require "pry-byebug"

class Scraper
  def add_books(doc, books, drop)
    doc.search("tr").drop(drop).map do |tr|
      title = tr.search("img").attribute("src").to_s.gsub("../..", "https://petit-prince-collection.com")
      language = tr.search(".story a").text.strip.capitalize

      book_info = {
        user: User.first,
        title: title,
        language: language,
      }

      books << book_info if book_info[:language] != ""
    end
  end

  def create_books
    books = []

    url = "https://petit-prince-collection.com/lang/collection.php?lang=fr"
    file = URI.open(url).read
    doc = Nokogiri::HTML(file)
    drop = 14

    # binding.pry

    add_books(doc, books, drop)

    url = "https://petit-prince-collection.com/lang/transcriptions.php?lang=fr"
    file = URI.open(url).read
    doc = Nokogiri::HTML(file)
    drop = 1

    add_books(doc, books, drop)

    books
  end
end

scrape = Scraper.new

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def full_name
    [first_name, last_name].join(" ")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [ :show, :edit, :update, :destroy ]
  def index
    @books = Book.all

    if params[:query].present?
      @books = @books.in_my_collection.where("language ILIKE ?", "%#{params[:query]}%")
    else
      @books
    end

    respond_to do |format|
      format.html
      format.text { render partial: "shared/list", locals: {books: @books}, formats: [:html] }
    end
  end

  def show() end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.save
    redirect_to book_path(@book)
  end

  def edit() end

  def update
    @book.update(book_params)
    redirect_to params[:previous_request]
  end

  def destroy
    @book.destroy
    redirect_to books_path, status: :see_other
  end

  def collection
    @books = Book.in_my_collection

    # if params[:query].present?
    #   @books = @books.where("language ILIKE ?", "%#{params[:query]}%")
    # else
    #   @books
    # end

    # respond_to do |format|
    #   format.html
    #   format.text { render partial: "shared/list", locals: {books: @books}, formats: [:html] }
    # end
  end

  def wishlist
    @books = Book.wishlist
  end

  private

  def book_params
    params.require(:book).permit(:title, :language, :language_details, :country, :date_of_acquisition, :number_of_books, :notes, :in_my_collection, :wishlist)
  end

  def set_book
    @book = Book.find(params[:id])
  end

  def query
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [ :home ]

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/collection.html.erb
<div class="container" data-controller="searchbar">

  <%= render "shared/searchbar", books: @books %>
  <%= render "shared/list", books: @books %>

</div>

app/views/books/edit.html.erb
<!--FORM MODAL -->
<div class = "container mt-3" style = "width: 500px">
  <div class="modal fade" id="updateModal-<%= book.id %>" tabindex="-1" aria-labelledby="updateModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="updateModalLabel">Modal title</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <!-- FORM -->
          <%= simple_form_for @book do |f| %>
            <div class="">
              <%= f.input :language, :label => "Langue" %>
              <%= f.input :language_details %>
              <%= f.input :date_of_acquisition %>
              <%= f.input :number_of_books %>
              <%= f.input :notes %>
              <%= f.input :in_my_collection %>
              <%= f.input :wishlist %>
              <%= hidden_field_tag :previous_request, request.referer %>
              <!-- f.input :country -> ne fonctionne pas -->

              <div class="form-actions d-flex justify-content-between align-items-end ">
                <%= f.submit "Sauvegarder" %>
                <%= link_to 'Back to books', books_path, class: "" %>
              </div>
            </div>
          <% end %>
          <!-- FORM -->
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>
</div>
<!--FORM MODAL -->

app/views/books/index.html.erb
<div class="container" data-controller="searchbar">

  <!-- <%= render "shared/searchbar" %> -->
  <%= render "shared/list" %>

</div>

app/views/books/wishlist.html.erb
<%= render "shared/list" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lepetitprince</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/flashes" %>
    <%= render "shared/navbar" %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </body>
</html>

app/views/pages/home.html.erb
<h1>Hello</h1>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_list.html.erb
<div class="container" data-searchbar-target="list">

  <% if current_page?('/index') %>

    <table class="table container">
      <thead>
        <tr>
          <th scope="col">Langue</th>
          <th scope="col">Titre</th>
          <th scope="col"></th>
        </tr>
      </thead>

      <tbody >
        <% @books.find_each do |book| %>
            <tr>
              <td>
                <%= book.language %>
                <% unless book.language_details.to_s.empty? || book.language_details.nil? %>
                  <a data-bs-toggle="modal" data-bs-target="#languageDetailsModal">
                    <i class="fa-solid fa-circle-info"></i>
                  </a>
                <% end %>
              </td>
              <td><img src="<%= book.title %>" alt=""></td>
              <td><%= book.notes %></td>
              <td>
                <% if book.user == current_user %>
                  <%= link_to(edit_book_path(book), class: "data-bs-toggle='modal' data-bs-target='#updateModal'") do %>
                    <i class="fa-solid fa-pencil"></i>
                  <% end %>
                <% end %>
              </td>
            </tr>
        <% end %>
      </tbody>
    </table>

  <% else %>

    <table class="table container">
      <thead>
        <tr>
          <th scope="col">Langue</th>
          <th scope="col">Titre</th>
          <th scope="col">Date d'aquisition</th>
          <th scope="col">Notes</th>
          <th scope="col"></th>
        </tr>
      </thead>

      <tbody>
        <% @books.find_each do |book| %>
          <tr>
            <td>
              <%= book.language %>
              <% unless book.language_details.to_s.empty? || book.language_details.nil? %>
                <a data-bs-toggle="modal" data-bs-target="#languageDetailsModal-<%= book.id %>">
                  <i class="fa-solid fa-circle-info"></i>
                </a>

                <!-- LanguageDetailsModal -->
                <div class="modal fade" id="languageDetailsModal-<%= book.id %>" tabindex="-1" aria-labelledby="languageDetailsModalLabel" aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="languageDetailsModalLabel">Info sur la langue</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                        <%= book.language_details %>
                      </div>
                    </div>
                  </div>
                </div>
                <!-------------------------->

              <% end %>
            </td>
            <td><img src="<%= book.title %>" alt=""></td>
            <td><%= book.date_of_acquisition %></td>
            <td><%= book.notes %></td>
            <td>
              <% if book.user == current_user %>
                <a data-bs-toggle="modal" data-bs-target="#updateModal-<%= book.id %>">
                  <i class="fa-solid fa-pencil"></i>
                </a>

                <!--FormModal -->
                  <div class="modal fade" id="updateModal-<%= book.id %>" tabindex="-1" aria-labelledby="updateModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" id="updateModalLabel">Éditer le livre</h5>
                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                          <!-- Form -->
                          <%= simple_form_for book do |f| %>
                            <div class="">
                              <%= f.input :language_details %>
                              <%= f.input :date_of_acquisition %>
                              <%= f.input :number_of_books %>
                              <%= f.input :notes %>
                              <%= f.input :in_my_collection %>
                              <%= f.input :wishlist %>
                              <%= hidden_field_tag :previous_request, request.referer %>
                              <!-- f.input :country -> ne fonctionne pas -->
                            </div>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-primary">
                                <%= f.submit "Sauvegarder" %>
                              </button>
                            </div>
                          <% end %>
                          <!-- Form -->
                        </div>
                      </div>
                    </div>
                  </div>
                <!--FormModal -->

              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

  <% end %>

</div>

app/views/shared/_modals.erb
<!-- LanguageDetailsModal -->
<div class="modal fade" id="languageDetailsModal" tabindex="-1" aria-labelledby="languageDetailsModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="languageDetailsModalLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

<!-- UpdateModal qui ne fonctionne pas -->
<div class="modal fade" id="updateModal" tabindex="-1" aria-labelledby="updateModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="updateModalLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "/", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Collection", collection_books_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Vue d'ensemble", books_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <div class="dropdown-toggle m-2" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.full_name %>
            </div>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuLink">
              <li><%= link_to "Wishlist", wishlist_books_path, class: "dropdown-item" %></li>
              <li><%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_searchbar.html.erb
  <%= form_with url: books_path, method: :get, html: {class: "mb-4", data: {searchbar_target: "form"}} do |f| %>
    <%= f.text_field :query,
                     class: "form-control",
                     placeholder: "Cherchez une langue...",
                     value: params[:query],
                     data: {
                      searchbar_target: "input",
                      action: "keyup->searchbar#update"
                    } %>
  <% end %>

app/views/shared/_show_language_details.erb
<!-- LanguageDetailsModal -->
<div class="modal fade" id="languageDetailsModal-<%= book.id %>" tabindex="-1" aria-labelledby="languageDetailsModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="languageDetailsModalLabel">Info sur la langue</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= book.language_details %>
      </div>
    </div>
  </div>
</div>
<!-- -->

<!-- UpdateModal qui ne fonctionne pas -->
<div class="modal fade" id="updateModal" tabindex="-1" aria-labelledby="updateModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="updateModalLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>